### ISSUE TITLE
Add support for BOSS quasar catalogs

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bossdata#11]
Questions to address:
- What files need to be mirrored?
- Is additional version info beyond the `$BOSS_*` env vars required to fully specify a catalog?
- Is the metadata small enough to use directly from the FITS file or do we need another sqlite db for this? 
- Do we need to support queries across spAll and the quasar catalog?  How do we do this?

**Comment by dmargala** [comment]
The BOSS DR12 quasar catalog is documented [here](http://www.sdss.org/dr12/algorithms/boss-dr12-quasar-catalog/). The main catalog file is 513Mb and its SAS path is `/sas/dr12/boss/qso/DR12Q/DR12Q.fits`. The data model for this file is [here](http://data.sdss3.org/datamodel/files/BOSS_QSO/DR12Q/DR12Q.html).
