### ISSUE TITLE
how to get absolute path of local files

### ISSUE THREAD

**Issue by dmargala** [dkirkby/bossdata#19]
I would expect the default usage of a Finder object is to construct paths to local files but this does not seem to be the case.

For example, I have my set up my environment with the following:

```
export BOSS_LOCAL_ROOT=/Users/daniel/data
export BOSS_DATA_URL=http://dr12.sdss3.org
export BOSS_SAS_PATH=/sas/dr12/boss
export BOSS_REDUX_VERSION=v5_7_0
```

To get the path of the spAll, I tried:

```
>>> finder = bossdata.path.Finder()
>>> finder.get_sp_all_path()
'/sas/dr12/spectro/redux/v5_7_0/spAll-v5_7_0.fits'
```

but it does not prepend the local root path, as I would expect.

I see that the local/remote distinction is handled by the Manager class. So the following returns what I want:

```
>>> finder = bossdata.path.Finder()
>>> manager = bossdata.remote.Manager()
>>> manager.local_path(finder.get_sp_all_path())
'/Users/daniel/data/sas/dr12/boss/spectro/redux/v5_7_0/spAll-v5_7_0.dat.gz'
```

but is that the intended usage?

**Comment by dkirkby** [comment]
Yes, that's the intended usage.

The `Finder` only uses `$BOSS_SAS_PATH` and `$BOSS_REDUX_VERSION` and provides methods that generate generic paths (that exist under `$BOSS_DATA_URL` and `$BOSS_LOCAL_ROOT`). The finder never interacts with any remote or local filesystems.

The `Manager` only uses `$BOSS_DATA_URL` and `$BOSS_LOCAL_ROOT` and knows how to turn a generic path into either a URL or a local path, and is responsible for interacting with the remote and local filesystems.

The usual pattern is (where, so far, X = `spec`, `plate_plan`, `sp_all`):

```
remote_name = finder.get_X_path(...)
local_name = mirror.get(remote_name)
obj = XFile(local_name)
```

where the second line does the actual download, if necessary, and the constructor in the last line actually opens and interprets the locally mirrored file (for `spec` and `plate_plan`).

Any suggestions for making this more intuitive / obvious?
