### ISSUE TITLE
add default filename for bossplot

### ISSUE THREAD

**Issue by dcunning11235** [dkirkby/bossdata#24]
Feature-add:  a default filename (perhaps plate_mjd_fiber_plot.png) to bossplot when --save-plot specified with no argument.  Would make scripting with bossplot slightly more convenient.

**Comment by dkirkby** [comment]
You can add the "enhancement" label (from the right-hand menu) for issues like this.

**Comment by dkirkby** [comment]
My first reaction is that this feature is not compatible with how the python argparse module works, but I just learned about the [nargs](https://docs.python.org/2.7/library/argparse.html#nargs) option which seems to solve this problem nicely.

**Comment by dkirkby** [comment]
Fixed by #26
