### ISSUE TITLE
Cosmetic improvements to bossplot

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bossdata#27]
Ideas to consider:
- optional plot label that defaults to plate-mjd-fiber, but can also interpolate values from spAll into a format string (but will not auto-download spAll)
- override automatic yaxis limits via command-line options
- wavelength (vertical) grid lines

Add your own ideas below.

**Comment by dcunning11235** [comment]
- Add option to label spectra features (from spec\* files, HDU3)
  - Can this be done (well) automatically?
  - Would want manual control (select some subset/label only a few specific lines), so is doing it automatically needed at all?
- Draw the average line inside/over-top of the error bars/shading
- Optionally specify the wavelength range to plot over
- Optionally specify a scaling factor for the y-axis

**Comment by dkirkby** [comment]
This is mostly addressed with #59.  We still need to implement the labeling option.

**Comment by dkirkby** [comment]
I am hoping to close this out with the new commits to #70 (after it gets merged).
