### ISSUE TITLE
os.path.join on Windows to create urls?

### ISSUE THREAD

**Issue by dmargala** [dkirkby/bossdata#43]
I was thinking about this over my morning coffee... 

If `remote_path` is built using `os.path.join` on a Windows system, it will contain forward slashes. The Manager class will then try to construct a url with this forward slashed path. Is that going to be okay?

**Comment by dcunning11235** [comment]
A quick check with some hardcoded `requests` indicates, "No."  Backslashes (escaped nor not) in the URL are not automatically converted to forward slashes.

**Comment by dkirkby** [comment]
It looks like the `posixpath` module solves this problem for us: on posix systems, `os.path` is an alias for `posixpath`, but is also available on windows systems.  The `posixpath` docstring even mentions this use case specifically:

```
import posixpath
posixpath?
...
posixpath?
Type:        module
String form: <module 'posixpath' from '/Users/david/anaconda/lib/python2.7/posixpath.pyc'>
File:        ~/anaconda/lib/python2.7/posixpath.py
Docstring:
Common operations on Posix pathnames.

Instead of importing this module directly, import os and refer to
this module as os.path.  The "os.path" name is an alias for this
module on Posix systems; on other systems (e.g. Mac, Windows),
os.path provides the same operations in a manner specific to that
platform, and is an alias to another module (e.g. macpath, ntpath).

Some of this can actually be useful on non-Posix systems too, e.g.
for manipulation of the pathname component of URLs.
```

However, this means that we need to build paths twice since they will be used both in the local filesystem and also to build a remote URL.

**Comment by dmargala** [comment]
Perhaps we can leave Finder alone and Manager just needs to clean things up a bit before using the `remote_path`. For example:

```
>>> remote_path = r'http://sdss3.data.org\sas\dr12\boss'
>>> print remote_path
http://sdss3.data.org\sas\dr12\boss
>>> print posixpath.join(*remote_path.split('\\'))
http://sdss3.data.org/sas/dr12/boss
```

**Comment by dkirkby** [comment]
That's a good idea.

**Comment by dmargala** [comment]
Actually, it looks like we should use `posixpath` in Finder. Then `Manager.local_path()` is the only place we need to clean the path.
