### ISSUE TITLE
Determining if a given fiber is pointing at the sky

### ISSUE THREAD

**Issue by dcunning11235** [dkirkby/bossdata#44]
Is there a better way of determining if a given fiber is pointing at the sky than looking for ZWARNING values in (1,5) that anyone is aware of?  I see that I can determine from spPlate (OBJTYPE startswith 'SKY'), but I don't know that this is actually 'better' as it involves ~100MB download per plate and some extra/new work. :)

This is fine to start work with, just wondering if I'm missing a better solution.

**Comment by dmargala** [comment]
A lot of information is duplicated across the entire sdss data model. The spAll catalog file will typically have most of the information you want. If you look at [this page](http://data.sdss3.org/datamodel/files/BOSS_SPECTRO_REDUX/RUN2D/spAll.html), you can see that spAll has the OBJTYPE keyword and that it is propagated from spZbest.

**Comment by dkirkby** [comment]
Even better, OBJTYPE is in the lite meta file.

**Comment by dcunning11235** [comment]
doh!
