### ISSUE TITLE
Optional argument for bossquery

### ISSUE THREAD

**Issue by belaa** [dkirkby/bossdata#49]
Is there a way of downloading data from the full db for a specific observation period without extending --max-rows to include those dates (and thus increasing the file size)? Or do we use lite files for this purpose?

**Comment by dkirkby** [comment]
The easiest way to do this is to specify the period you are interested in using the MJD variable. For example, starting with this query which finds the first 10K quasars:

```
bossquery --where 'OBJTYPE="QSO"' --save qso.dat --max-rows 10000
```

The last entries have MJD = 55178.  To just pick out quasars from the week starting on 55178, you could use:

```
bossquery --where 'OBJTYPE="QSO" and MJD=55178' --save qso.dat
```

which finds all 506 quasars from this day.  You can also include a range of dates in your `where` clause, for example:

```
bossquery --where 'OBJTYPE="QSO" and MJD between 55178 and 55180' --save qso.dat
```

Any of the `qso.dat` files generated from the commands above can be fed to `bossfetch`, where you get lite files by default, unless you add the `--full` option.
