### ISSUE TITLE
Test and document working with multiple data sources

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bossdata#50]
We have been working with the public DR12 release so far, but the code is setup to support other data sources via the `$BOSSS_*` env vars and their optional constructor-arg equivalents.  This issue is to test and document working with other data sources and, if necessary, update the code to improve support for this.

**Comment by dkirkby** [comment]
The public DR12 release is specified using:

```
export BOSS_SAS_PATH=/sas/dr12/boss
export BOSS_REDUX_VERSION=v5_7_0
export BOSS_DATA_URL=http://dr12.sdss3.org
```

These variables specify defaults used by `bossdata.path.Finder` and `bossdata.remote.Manager`, but they can also be overridden with optional constructor args, e.g.

```
finder = bossdata.path.Finder(sas_root=..., redux_version=...)
mirror = bossdata.remote.Manager(data_url=...)
```

Note that the bin scripts (`bossquery`, `bossfetch`, `bossplot`) only use the env vars and do not provide cmd-line args to override them (should we add these?)  Instead, you can use, e.g. (in bash)

```
BOSS_REDUX_VERSION=v5_7_2 bossquery ...
```

**Comment by dkirkby** [comment]
### Use case 1: DR12 SEQUELS

Documented [here](http://www.sdss.org/dr12/algorithms/ancillary/boss/sequels/). Change redux version from 5_7_0 to 5_7_2:

```
export BOSS_SAS_PATH=/sas/dr12/boss
export BOSS_REDUX_VERSION=v5_7_2
export BOSS_DATA_URL=http://dr12.sdss3.org
```

Quoting from [here](http://www.sdss.org/dr12/data_access/bulk/):

```
For BOSS, the main galaxy clustering survey is entirely contained in v5_7_0.
After the main survey was finished, ancillary programs continued —
these were processed as v5_7_2, which is the same code but a different
processing version number to keep the datasets distinct.  The SEQUELS
ancillary program has plates in both v5_7_0 and v5_7_2.
```

**Comment by dkirkby** [comment]
### Use case 2:  SDSS-I/II spectra

Change instrument (in `SAS_PATH`) from boss to sdss and change redux version from 5_7_0 to 26:

```
export BOSS_SAS_PATH=/sas/dr12/sdss
export BOSS_REDUX_VERSION=26
export BOSS_DATA_URL=http://dr12.sdss3.org
```

This provides spectra for plates 0266 - 3006.

**Comment by dkirkby** [comment]
### Use case 3: eBOSS pre-release data

The URL for the latest release is https://data.sdss.org/sas/ebosswork/eboss/spectro/redux/v5_8_0/ which can be accessed using:

```
export BOSS_SAS_PATH=/sas/ebosswork/eboss
export BOSS_REDUX_VERSION=v5_8_0
export BOSS_DATA_URL=http://data.sdss.org
```

This will not work as-is until we add support for for authentication.  Probably the easiest way to do this is to add optional extra fields to `$BOSS_DATA_URL`, e.g.

```
export BOSS_DATA_URL=http://data.sdss3.org:<username>:<password>
```

**Comment by dmargala** [comment]
### Use case 4: BOSS private data

Internal pipeline reductions are accessible at URL's such as http://data.sdss3.org/sas/bosswork/boss/spectro/redux/test/dmargala/redux/v5_7_0/. Note that this URL requires authentication.

Can `BOSS_REDUX_VERSION` be used in the following manner?

```
export BOSS_SAS_PATH=sas/bosswork/boss
export BOSS_REDUX_VERSION=test/dmargala/redux/v5_7_0
export BOSS_DATA_URL=http://data.sdss3.org
```

**Comment by dcunning11235** [comment]
I started running through UC 1, SEQUELS.

Only one minor issues so far:  the default plot for bossplot (executing `bossplot` with not options) fails with a HTTP 404, presumably because the default plate/mjd/fiber don't exist in v5_7_2.  This is minor, and I think the easiest way to deal with this is just to output the help message rather than do a default plot.  Reasonable?

Different subject:  Not sure if this is unique to SEQUELS or not, but the survey spans two datasets.  The way we are doing things now, this means SEQUELS data are in two (sets) of DB files, etc. with no particularly convenient way to e.g. execute a query across the whole survey.  Plotting from the two sets also requires changing the env var (or overriding on the command line) for every plot.  In this case, it seems like we'd want to combine the datasets (DB's, local files, etc.).  But that involves a lot of changes; perhaps its somewhat easier to specify some argument outside the query input that causes multiple datasets to be used (e.g. --survey SEQUELS)

**Comment by dkirkby** [comment]
The reason for hardcoding a default plate-mjd-fiber is so that we have some simple command you can type after you first install or upgrade that does something non-trivial and doesn't require downloading any big file (so `bossquery` is not a good candidate for this).  You have found a weakness with this that could partially fixed by #53, but is still problematic.

You could argue that using non-default env vars means you know what you are doing and can deal with a good error message, e.g.

```
The requested plate-mjd-fiber = ... is not available with these settings:
  BOSS_SAS_ROOT = ...
  ...
```

Along these lines, perhaps the recommended default env vars should actually be hardcoded somewhere, so that you don't need to set any env vars for `bossplot` to work after an initial install?

**Comment by belaa** [comment]
I'm trying to run case 2. In .bashrc I have: 

```
export BOSS_LOCAL_ROOT=/Users/bela/Desktop/bossdata
export BOSS_DATA_URL=http://dr12.sdss3.org
export BOSS_SAS_PATH=/sas/dr12/sdss
export BOSS_REDUX_VERSION=26

```

Yet I keep getting:

```
bossquery --full --what MJD --where "" --save test.dat
HTTP request returned error code 404 for http://dr12.sdss3.org/sas/dr12/sdss/spectro/redux/26/spAll-26.fits.

```

**Comment by dkirkby** [comment]
You just discovered that the SDSS-I/II reductions do not have an spAll file, which I didn't know!

**Comment by dmargala** [comment]
I think this is what you want

http://data.sdss3.org/datamodel/files/SPECTRO_REDUX/specObj.html

**Comment by dkirkby** [comment]
Here is a working example of use-case 2 that uses the DR12 quasar catalog for its meta data:

```
# Use default DR12 setup
export BOSS_SAS_PATH=/sas/dr12/boss
export BOSS_REDUX_VERSION=v5_7_0
export BOSS_DATA_URL=http://dr12.sdss3.org

# Find the 25,275 BOSS quasars that were previously observed in SDSS-I
bossquery --verbose --quasar-catalog --what "PLATE,MJD,FIBER,PLATE_DR7,MJD_DR7,FIBERID_DR7,THINGID" --where "SDSS_DR7<>0" --max-rows 30000 --save dr7_quasars.dat

head -2 dr7_quasars.dat
PLATE MJD FIBER PLATE_DR7 MJD_DR7 FIBERID_DR7 THING_ID
6177 56268 386 750 52235 82 235532867

bossplot --plate 6177 --mjd 56268 --fiber 386 --save-plot qso-235532867-56268.png

# Use SDSS-I data
export BOSS_SAS_PATH=/sas/dr12/sdss
export BOSS_REDUX_VERSION=26

bossplot --plate 750 --mjd 52235 --fiber 82 --save-plot qso-235532867-52235.png
```

The resulting plots are below:
![qso-235532867-56268](https://cloud.githubusercontent.com/assets/185007/8398885/a45041e2-1db5-11e5-945e-a901df2abb4a.png)
![qso-235532867-52235](https://cloud.githubusercontent.com/assets/185007/8398886/acadb1a8-1db5-11e5-97ff-7bc60117900b.png)

Note that I had to change `path.Finder` to prepend a zero to plate numbers < 1000 for this to work, which is on my issue branch, so the last `bossplot` command will fail on `master` until this is merged.

**Comment by dkirkby** [comment]
@dmargala We seem to be suffering from YAMS: yet another meta-data source.  I guess we can re-use the pattern you established for making the quasar catalog available, but do we really want to add `specobj_catalog` and `specobj_catalog_name` args / parameters everywhere, or should we revisit how this is handled?  Are there any more catalogs we should be planning for?

**Comment by dkirkby** [comment]
Still on use-case 2, I just added (on branch #50) options to override the default column names used to identify the plate,mjd,fiber in the file that `bossfetch` reads.  This enables `bossfetch` to use the columns with `_DR7` appended from the DR12 quasar catalog:

```
% head dr7_quasars.dat
PLATE MJD FIBER PLATE_DR7 MJD_DR7 FIBERID_DR7 THING_ID
6177 56268 386 750 52235 82 235532867
6513 56543 892 2822 54389 315 328376968
4216 55477 758 387 51791 531 116880826
```

like this:

```
export BOSS_SAS_PATH=/sas/dr12/sdss
export BOSS_REDUX_VERSION=26
bossfetch --plate-name PLATE_DR7 --mjd-name MJD_DR7 --fiber-name FIBERID_DR7 dr7_quasars.dat
```

**Comment by dmargala** [comment]
There are indeed other catalogs that might be useful. Yesterday, I added an option in my local repo to use query the [platelist catalog](http://data.sdss3.org/datamodel/files/BOSS_SPECTRO_REDUX/RUN2D/platelist.html) (I wanted the list of (ra,dec) for all the plate centers).

We probably don't want to keep adding those args everywhere.

Perhaps we just need a generic option to specify a `remote_path` of catalog. The database class doesn't really need to know about spAll, quasars, or platelist; just the catalog file type. The `renaming_rules` and `primary_key` would probably be specified by options as well.

**Comment by dkirkby** [comment]
Here is a working example for use-case 3 (eBOSS private data):

```
export BOSS_SAS_PATH=/sas/ebosswork/eboss
export BOSS_REDUX_VERSION=v5_8_0
export BOSS_DATA_URL=http://data.sdss.org%USER%PW
bossplot --verbose --cframe --plate 8054 --mjd 57194 --fiber 100 --exposure 0
```

The plot is below.  Notes:
- This test-release does not have individual spec or spec-lite files available, so I am using a cFrame file instead.  This means that we have no access to coadds until we resolve #28.
- USER and PW above should be replaced with the SDSS-IV private account info.
- I used the `%` separator since this does not need to be escaped when setting the variable in bash.
- Code for this is currently only on my topic branch.
  ![8054-57194-100-exp0](https://cloud.githubusercontent.com/assets/185007/8399323/83a0e00e-1dc0-11e5-800e-23695f5e02b8.png)

**Comment by dkirkby** [comment]
Still on use-case 3, here is an example of finding the 7,207 eBOSS quasars (in v5_8_0) that were previously observed by BOSS or SEQUELS:

```
export BOSS_SAS_PATH=/sas/ebosswork/eboss
export BOSS_REDUX_VERSION=v5_8_0
export BOSS_DATA_URL=http://data.sdss.org%USER%PW
bossquery --full --what 'PLATE,MJD,FIBER,THING_ID,Z,OBJTYPE,EBOSS_TARGET0,EBOSS_TARGET1' --where 'CLASS="QSO" and ZWARNING=0 and Z_ERR>0 and (EBOSS_TARGET0&4096>0 or EBOSS_TARGET1&4096>0)' --max-rows 10000 --print --save eboss-repeats.dat
```

The value 4096 above corresponds to QSO_REOBS = QSO1_REBOS = (1<<12) defined for [EBOSS_TARGET0](https://bossdata.readthedocs.org/en/latest/src/bossdata.bits.html#bossdata.bits.EBOSS_TARGET0) and [EBOSS_TARGET1](https://bossdata.readthedocs.org/en/latest/src/bossdata.bits.html#bossdata.bits.EBOSS_TARGET1).

Plot the last object found (since the first object has EBOSS_TARGET1=0 so was previously observed in SEQUELS, not the main BOSS survey) in this list using the eBOSS CFrame file (until #28 is resolved):

```
bossplot --plate 8498 --mjd 57105 --fiber 985 --cframe --exposure 0 --save-plot qso-438142735-57105-exp0.png
```

![qso-438142735-57105-exp0](https://cloud.githubusercontent.com/assets/185007/8412426/cad5fb7a-1e3e-11e5-9cec-bcdd7c66b2bf.png)

To plot the same object observed by BOSS, we first need to find its plate-mjd-fiber based on its THING_ID= 438142735.  This is faster using the quasar catalog (until #52 is resolved):

```
export BOSS_SAS_PATH=/sas/dr12/boss
export BOSS_REDUX_VERSION=v5_7_0
export BOSS_DATA_URL=http://dr12.sdss3.org
bossquery --quasar-catalog --where THING_ID=438142735 --print
```

Surprisingly, this THING_ID is not in the quasar catalog!  Try the (much slower) query on the full db:

```
bossquery --full --what 'PLATE,MJD,FIBER,ZWARNING,OBJTYPE,CLASS' --where THING_ID=438142735 --print
```

Hmm, not there either.  I will follow up on this with the eBOSS pipeline folks.
