### ISSUE TITLE
Error in url path for sdss-I data

### ISSUE THREAD

**Issue by belaa** [dkirkby/bossdata#58]
I've set my environment variables to those specified for SDSS-I/II spectra (as given on http://bossdata.readthedocs.org/en/latest/envvar.html#sdss-i-ii-spectra), yet when I call bossquery I'm still getting an error: 

```
HTTP request returned error code 404 for http://dr12.sdss3.org/sas/dr12/sdss/qso/DR12Q/DR12Q.fits.
```

I feel like this should be the path to the data:

```
http://dr12.sdss3.org/sas/dr12/sdss/spectro/redux/26/
```

Can anyone suggest why the first path above is trying to access DR12 data/why my path isn't given by the second one?

**Comment by dmargala** [comment]
Can you include the command you are trying to run?

It looks like you are trying to query the quasar catalog which is a BOSS product.

**Comment by belaa** [comment]
I used the working-example for use case 2 from   https://github.com/dkirkby/bossdata/issues/50#issuecomment-116361268, however I just learned that since there is no spAll file I can only access individual spectra.
