### ISSUE TITLE
Downloading data from server to personal computer

### ISSUE THREAD

**Issue by dwkang1** [dkirkby/bossdata#65]
When using the --save command, it seems to download the file to the server onto my account. Is there a way to save it onto my own desktop to use in python?

**Comment by dkirkby** [comment]
Can you provide the command that you used?  The same command should work the same way on your own desktop, so that would be one solution. You can also copy files between your desktop and the server using [some tools built on ssh](https://help.ubuntu.com/community/SSH/TransferFiles).

**Comment by dwkang1** [comment]
The command I used was:

bossquery --full --quasar-catalog --where 'PLATE>1000' --what PLATE,MJD,FIBER,RA,DEC --sort 'RA,DEC' --print --save firstfile.dat

This saves the file onto the directory:     /home/dkang

I tried using some terminal commands to switch directories to my computer, but since I'm signed on the server, I don't think there was a path to my desktop.

**Comment by dkirkby** [comment]
Try the following command on your desktop to copy the file from the server:

```
scp dkang@darkmatter.ps.uci.edu:firstfile.dat .
```

**Comment by dwkang1** [comment]
It doesn't recognize the command and outputs a list of commands for scp. It gives me:

usage: scp [-1246BCEpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2

The syntax seems right but my Terminal doesn't seem to be recognize it. Maybe it's because of one of the server's settings that prevents it from interacting with the computer's directories?

**Comment by dkirkby** [comment]
@dwkang1 Is this resolved now?

**Comment by dwkang1** [comment]
yes it is
