### ISSUE TITLE
Use full file if already downloaded and lite file is requested

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bossdata#7]
Can probably implement this by generalizing the remote path arg of `remote.Manager.get()` to take a list of paths with the following logic:
- Return the first path in the list that is already downloaded, if any.
- Otherwise, download the first item in the list (which would be the lite version).

This could then be used in `meta` and `spec` to avoid downloading a lite file when the full file is already downloaded.

**Comment by dcunning11235** [comment]
I'm assuming this actually cover DB's and files.  So, given a "lite request" via e.g. `bossquery`, then depending on existence of files we take action following:

| Lite DB | Lite File | Full DB | Full File | ACTION |
| --- | --- | --- | --- | --- |
| 1 | * | * | * | Use Lite DB |
| 0 | * | 1 | * | Use Full DB |
| 0 | 1 | 0 | * | Use Lite File/Build Lite DB |
| 0 | 0 | 0 | 1 | Use Full File/Build Full DB |
| 0 | 0 | 0 | 0 | Download Lite File/Build Lite DB |

**Comment by dkirkby** [comment]
The original issue covers both meta db and spec files.  Your updates to `remote` cover both cases nicely, but we either need to split the spec files into a separate issue or also address them.

The case of having a the metadata file downloaded but no corresponding sqlite3 db is unlikely (since these steps normally occur together in `create_meta_*`), so I hadn't considered this possibility and would be willing to ignore it for simplicity.  However, if your code handles this already, that's even better.

**Comment by dcunning11235** [comment]
Closing; changes (DB and spec) merged in.
