### ISSUE TITLE
Unable to find THING_ID value in SDSS spec files

### ISSUE THREAD

**Issue by belaa** [dkirkby/bossdata#71]
Is THING_ID expected to be in the metadata for spec files from SDSS I/II runs? I'm looking at the spec data model and it says that THING_ID values should be contained in HDU 0. I've found this to be true for files from BOSS but cannot seem to find that information in any of the HDU's for pre-BOSS files. I was also unable to find a column in the SDSS spec file with the same THING_ID value as the 're-observed' qso in BOSS. 

For example, for `spec-3826-55563-0190.fits` in BOSS: 

`hdulist[0].header['THING_ID']= 88198150`

yet for the corresponding qso in SDSS `spec-0266-51630-0280.fits`:

`hdulist[2].data.THING_ID[0]`
`AttributeError: record array has no attribute THING_ID`

Should I be looking for a different column name or is this information not accessible in these files?

**Comment by dkirkby** [comment]
I haven't tried to reproduce this issue yet but I wanted to check something first: why are you using a different access pattern for the two files?  I would have expected `hdulist[0].header['THING_ID']` to work in both files since they have the same data model.

**Comment by belaa** [comment]
I meant to use the initial `hdulist[0].header['THING_ID']` for both, the other one was something I was testing on my own and incorrectly pasted above. I've tried both and neither seem to work..

**Comment by dkirkby** [comment]
The [data model](http://dr12.sdss3.org/datamodel/files/BOSS_SPECTRO_REDUX/RUN2D/spectra/PLATE4/spec.html) claims that:

```
PLUG_RA, PLUG_DEC, THING_ID, FIBERID: added from spAll
```

Can you check if `PLUG_RA` is also missing from the SDSS-I files?

**Comment by belaa** [comment]
`PLUG_RA` is not missing

**Comment by dkirkby** [comment]
Can you check `PLUG_DEC` and `FIBERID` and then you could post a question to the e-boss pipeline mailing list.

**Comment by belaa** [comment]
I just checked them and they both work. I'll go ahead and post the question

**Comment by dkirkby** [comment]
Based on the reply you got, it sounds like there is nothing to fix in `bossdata` and we have learned that `THING_ID` is not useful for matching objects between SDSS-I/II - BOSS - eBOSS.  If we did need an integer identifier for this purpose, a 64-bit healpix bin number would work nicely.
