### ISSUE TITLE
Add option to retrieve ivar with get_valid_data methods

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bossdata#86]
The `get_valid_data` methods from `SpecFile`, `PlateFile` and `FrameFile` all return `dflux` calculated from internal ivar values.  This is often what you want, but sometimes `ivar` is more useful, e.g., when averaging spectra.  I propose to keep `dflux` as the default, but add an option to get `ivar` instead of (or in addition to?) `dflux`.

**Comment by dmargala** [comment]
Similarly, sometimes `loglam` is useful (instead of `wavelength`) for compatibility with already written software.

**Comment by dkirkby** [comment]
Yes, good point.  That should clearly be an either/or option.  Can you think of a use case for returning both ivar and dflux?

**Comment by dcunning11235** [comment]
One case where both are used, though getting ivar would be sufficient:  averaging together fluxes (ivar as weights) and also outputting the combined sigma/dflux.

**Comment by dkirkby** [comment]
I am working on the averaging use case right now to try and figure this out...

**Comment by dkirkby** [comment]
Closed with PR #88
