### ISSUE TITLE
What is a TraceSet?

### ISSUE THREAD

**Issue by dcunning11235** [dkirkby/bossdata#93]
This is a curve fit to...flux?  Or not a fit at all, something else?

**Comment by dkirkby** [comment]
A traceset gives the parameters of a curve fit to each fiber's trace on the CCD, i.e., pixel offset as a function of wavelength.  The fits are based on "flat" calibration exposures, which uniformly illuminate each trace, and "arc" exposures, which illuminate specific well-known frequencies.
